name: Publish package to npmjs
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Run test suite
        run: npm run test
      - name: Build package
        run: npm run build
      - name: Deploy patch version
        run: npm run deploy-patch-version
      - run: npm publish --access-public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
