name: Publish package to npmjs
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Run test suite
        run: npm run test
      - name: Build package
        run: npm run build
      - run: git config --global user.name "${{ github.actor }}"
      - run: git config --global user.email "github-action-${{ github.actor }}@users.noreply.github.com"
      - run: npm version ${{ github.event.release.tag_name }}
      - run: npm publish --access-public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
